### ISSUE TITLE
macOS: Permission denied: '/usr/local/LICENSE_BSD_3'

### ISSUE THREAD

**Issue by ax3l** [scikit-build/cmake-python-distributions#277]
Since the `3.24.0` release, I see the following issue on macOS in my CI:
```console
python3 -m pip install -U pip setuptools wheel pytest
python3 -m pip install -U cmake
```
```
...
packages: cmake
ERROR: Could not install packages due to an OSError: [Errno 13] Permission denied: '/usr/local/LICENSE_BSD_3
Consider using the `--user` option or check the permissions.
```

**Comment by ax3l** [comment]
Reproducer GH Action:
```yaml
name: 🍏 macOS

on: [push, pull_request]

concurrency:
  group: ${{ github.ref }}-${{ github.head_ref }}-macos
  cancel-in-progress: true

env:
  CXXFLAGS: "-Werror -Wshadow -Woverloaded-virtual -Wextra-semi -Wunreachable-code -fno-operator-names -Wno-pass-failed"

jobs:
  appleclang:
    name: AppleClang@12.0 w/o MPI
    runs-on: macos-latest
    if: github.event.pull_request.draft == false
    steps:
    - uses: actions/checkout@v2
    - name: Dependencies
      run: .github/workflows/dependencies/dependencies_mac.sh
    - name: Build & Install
      run: |
        python3 -m pip install -U pip setuptools wheel pytest
        python3 -m pip install -U cmake
```
